# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            R Data
tagline:          'David Robinson and Neo Christopher Chung'
description:      'Data Analysis and Visualization Using R'
url:              http://dgrtwo.github.io/

author:
  name:           'David Robinson'
  url:            http://dgrtwo.github.io/

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/jtleek/jtleek.github.io